#include <stdio.h>
#include <stdlib.h>

typedef struct {	int chave;} TItem;typedef struct celula {	struct celula *pProx;	TItem item;} TCelula;typedef struct {	TCelula *pPrimeiro, *pUltimo;} TLista;
void iniciarLista (TLista *pLista);int isVazia (TLista *pLista);int inserirFim (TLista *pLista, TItem x);int inserirAposE (TLista *pLista, TItem x, int p);int removerPrimeiro (TLista *pLista, TItem *pX);int removerUltimo (TLista *pLista, TItem *pX);void imprimir (TLista *pLista);
void iniciarLista (TLista *pLista) {	pLista->pPrimeiro = NULL;	pLista->pUltimo = NULL;}int isVazia (TLista *pLista) {	return pLista->pPrimeiro == NULL;}
int inserirFim (TLista *pLista, TItem x) {	TCelula *novo = (TCelula *) malloc (sizeof (TCelula));	novo->item = x;	novo->pProx = NULL;		if (isVazia (pLista)) {		pLista->pPrimeiro = novo;	} else {		pLista->pUltimo->pProx = novo;	}	pLista->pUltimo = novo;		return 1;}	int inserirAposE (TLista *pLista, TItem x, int e) {	// Localizando a posicao que deve ser inserido o novo elemento	TCelula *pAux = pLista->pPrimeiro;	while (pAux != NULL && pAux->item.chave != e) {		pAux = pAux->pProx;	}		if (pAux == NULL) {		// Elemento E nao encontrado		return 0;	}		TCelula *novo = (TCelula *) malloc (sizeof (TCelula));	novo->item = x;	novo->pProx = pAux->pProx;	pAux->pProx = novo;		if (novo->pProx == NULL) {		// Foi inserido na ultima posicao		pLista->pUltimo = novo;	}		return 1;}
int removerPrimeiro (TLista *pLista, TItem *pX) {	if (isVazia (pLista))		return 0;	TCelula *pAux;	pAux = pLista->pPrimeiro;	*pX = pAux->item;	pLista->pPrimeiro = pAux->pProx;	free (pAux);	return 1;}int removerUltimo (TLista *pLista, TItem *pX) {	if (isVazia (pLista))		return 0;		TCelula *pAux = pLista->pPrimeiro;		// Ha apenas 1 elemento na lista	if (pAux->pProx == NULL) {		*pX = pAux->item;		free (pAux);		pLista->pPrimeiro = NULL;		pLista->pUltimo = NULL;	} else {		// Ha mais de um elemento na lista		// localizando a celula anterior ao ultimo elemento		while (pAux->pProx != pLista->pUltimo) {			pAux = pAux->pProx;		}		*pX = pAux->pProx->item;		free (pAux->pProx);		pAux->pProx = NULL;		pLista->pUltimo = pAux;	}		return 1;}	void imprimir (TLista *pLista) {	TCelula *pAux = pLista->pPrimeiro;		printf ("Itens na lista:\n");	while (pAux != NULL) {		printf ("%d\n", pAux->item.chave);		pAux = pAux->pProx;	}}

int main() {
	TLista lista;	iniciarLista (&lista);	printf("Vazia: %s\n", isVazia(&lista) == 1 ? "SIM":"NAO");	TItem item1, item2, item3;	item1.chave = 10;	inserirFim (&lista, item1);	item2.chave = -5;	inserirFim (&lista, item2);	item3.chave = 20;	inserirAposE (&lista, item3, item3.chave);	imprimir (&lista);	printf("Vazia: %s\n", isVazia(&lista) == 1 ? "SIM":"NAO");	TItem itemRemovido;	removerUltimo (&lista, &itemRemovido);	printf("Item removido: %d\n", itemRemovido.chave);	imprimir (&lista);
}
